version: '3.8'

services:
  mongodb-test:
    image: mongo:7.0
    container_name: mongodb-test-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret_password123
    command: [
      "--quiet", 
      "--setParameter", "logComponentVerbosity={network: {verbosity: -1}, accessControl: {verbosity: 0}, command: {verbosity: 0}}"
    ]
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "-u", "root", "-p", "secret_password123", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-test

  neo4j-test:
    image: neo4j:5.18
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_PLUGINS=["apoc"]
    networks:
      - app-test
    healthcheck:
      test:
        [
          "CMD",
          "cypher-shell",
          "-u",
          "neo4j",
          "-p",
          "password123",
          "--encryption",
          "false",
          "RETURN 1;"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-test

  api-test:
    image: entity-management-soc-test
    build: .
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - PYTHONPATH=/app:/app/backend
      - TESTING_IN_DOCKER=true
      - NEO4J_URI=bolt://neo4j-test:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password123
      - MONGO_URI=mongodb://root:secret_password123@mongodb-test:27017
      - MONGODB_DATABASE=test_db 
      - RESET_DB=true
      - SEED_NAME=TEST
      - GEMINI_API_KEY=None
    volumes:
      - .:/app
    networks:
      - app-test
    depends_on:
      neo4j-test:
        condition: service_healthy
      redis:
        condition: service_healthy
      mongodb-test:
        condition: service_healthy
    command: ["pytest", "-vs", "--cov=backend", "--cov-report=term-missing"]

networks:
  app-test:
    driver: bridge
